### ISSUE TITLE
Doesn't work with pylint

### ISSUE THREAD

**Issue by dgrant** [pyfocus/pylava#3]
I suspect it's because of this line: https://github.com/pyfocus/pylava/blob/dd43236b544890aeb33c2ea674eee8e93a265f98/pylava/lint/extensions.py#L40

where you're looking for "pylava.linter" instead of "pylama.linter"

**Comment by dgrant** [comment]
Still doesn't work after I do that, but it doesn't print the "WARNING:root:Linter `pylint` not found" error anymore.

**Comment by susam** [comment]
Hi @dgrant,

Thank you for reporting this issue. This issue demonstrates two separate problems:

  1. The extension for Pylint does not work. This is an issue in [Pylama_pylint](https://github.com/klen/pylama_pylint) due to which it is unable to initialize Pylint version 2.0 and later.
  2. Pylava does not report error when the extension for Pylint does not work. This is an issue in [Pylama](https://github.com/klen/pylama) and its fork [Pylava](https://github.com/pyfocus/pylava).

Both issues have been fixed now.

Since the first issue requires a fix in Pylama_pylint which is not being maintained anymore, this issue was fixed as follows:

- Forked Pylama_pylint into [Pylava_pylint](https://github.com/pyfocus/pylava_pylint).
- Updated the fork to depend on Pylava instead of Pylava (commit [3253b02][FIX1]).
- Fixed the Pylint initialization issue (commit [f715599][FIX2]).

The second issue was fixed as follows:

- Report any errors that occur in linters with a logging level of ERROR (commit [fc5708a][FIX3]).

Both fixes are available on PyPI now (as Pylava 0.2.1 and Pylava_pylint 0.0.1).

To install/upgrade and test it out, enter the following commands:

    pip install --upgrade pylava
    pip install --upgrade pylava_pylint
    pylava -l pylint

[FIX1]: https://github.com/pyfocus/pylava_pylint/commit/3253b02fdc1ca133c8b467962e38f0ece6bae49c
[FIX2]: https://github.com/pyfocus/pylava_pylint/commit/f7155998e8515dfcfbf0be3c0fc3d245ceaecc25
[FIX3]: https://github.com/pyfocus/pylava/commit/fc5708aad7da1ffcb96c21323ea695334a59e238

**Comment by dgrant** [comment]
Thanks @susam for fixing this!
